# Generated by Django 5.2.7 on 2025-10-17 19:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
        ("products", "0001_initial"),
    ]

    operations = []
